### PR TITLE
added class structure for charts

### PR DESCRIPTION
**Pull request by AhmetTanakol**
Added different types of charts as a part of initial structure

Refers to #6

### CODE REVIEW

**Review by hubjak — COMMENTED** [review]
Are you sure we should use classes? It should be a client library and therefore be able to run in all browsers
EDIT: Ok, never mind, I thought it was some brand-new feature, but obviously browser support is quite acceptable.

**Comment by AhmetTanakol** [comment]
Please check all the commits, it may look like too detailed, but I think it is better to have a defined structure (data and layout) for each chart. It will be easier for us to track what kind of data model and layout are needed to plot a chart. Of course, we are going to have a lot of improvements but at least this type of approach provides some information about charts.

**Review by ghost — APPROVED** [review]

**Comment by syxolk** [comment]
I don't think it's useful to have classes with getters and setters in JavaScript. Most of the time this just results in a lot of boilerplate (looking at you Java :angry: ).
Better think about the interfaces first.

**Comment by AhmetTanakol** [comment]
In order create interfaces, we need to use typescript. I think you dont want us use typescript.

**Comment by syxolk** [comment]
Oh, I don't mean actual interfaces (like provided by the language), just contracts.

**Pull request merged**
