### PR TITLE
initial project structure

### PR DESCRIPTION
**Pull request by AhmetTanakol**
Summary:
* created single page app to plot graphs
* added eslint configuration

### CODE REVIEW

**Comment by syxolk** [comment]
What's up with the other branch `initial_setup`?

**Comment by ghost** [comment]
The other branch was created during our team meeting yesterday. I will close it after i reviewed the improved one from Ahmet.

**Comment by AhmetTanakol** [comment]
Right now, we are trying to figure out what kind of approach we should apply. Once we agree on a structure, everyone will focus on his/her own tasks

**Comment by ghost** [comment]
please add the package.json

**Comment by AhmetTanakol** [comment]
updated

**Review by ghost — APPROVED** [review]

**Comment by syxolk** [comment]
You commited a git diff:
```
+<<<<<<< HEAD
+package.json
+
+=======
+>>>>>>> 42857bc6a2f1d8e358b06ada332a5ceaacd0fc45
```
https://github.com/Rostlab/JS18_ProjectB_Group3/pull/22/files#diff-a084b794bc0759e7a6b77810e01874f2R123

That also means you are ignoring package.json.

**Pull request merged**
