### PR TITLE
refactor regular expressions

### LINKED ISSUE #53: improve regex expressions for mapping user commands

### PR DESCRIPTION
**Pull request by AhmetTanakol**
* Input commands are more flexible. Searching a set of defined keywords in the given command. Removed matching of sentences.
* Updated unit tests
* Updated README

Fix #53

### CODE REVIEW

**Review by syxolk — APPROVED** [review]
I think, this is ok from a technical standpoint but not in accordance to the requirements. It's a bit too easy to just put every important value in quotation marks. I would be a lot nicer, if number or color values could be detected automatically. What do you think?

**Comment by AhmetTanakol** [comment]
I agree. I looked at some of the libraries that were shared in general channel. Compromise can detect some of the words in given string, but still it doesn't support finding color names and numbers. We can use compromise plugin which allows you to tag words, but again we end up using a list of predefined words.

**Comment by syxolk** [comment]
For colors you could use this package/list: https://www.npmjs.com/package/css-color-names

**Comment by AhmetTanakol** [comment]
Thank you for your suggestion. I added it into our project. I removed usage of quotation marks for number and color detection. Also I added another regex expression to detect numbers, decimals in a given input.

**Pull request merged**
